apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuekcal
spec:
  selector:
    matchLabels:
      app: vuekcal
  replicas: 2
  template:
    metadata:
      labels:
        app: vuekcal
    spec:
      containers:
        - name: search
          image: 806803862815.dkr.ecr.eu-central-1.amazonaws.com/k8s-search
          ports:
            - containerPort: 3000